# Numpy 套件

In [2]:
a=[1,2,3,4,5]
print(a*3)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


# numpy套件的ndarray 型態 ，提供element-wise的操作

In [6]:
import numpy as np
b=np.array([1,2,3,4,5])
print(b*3)

[ 3  6  9 12 15]


In [7]:
print(type(b))
print(b.ndim) #ndarray的維度
print(b.shape) #ndarray的shape
print(b.dtype) #ndarray 的資料型態

<class 'numpy.ndarray'>
1
(5,)
int32


In [8]:
print(np.zeros(6)) #產生六個元素均為0的一維array
print(np.zeros((3,6))) #產生18個元素均為0的二維array
print(np.zeros((2,3,6))) #產生36個元素均為0的三維array

[0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]


In [10]:
a=np.zeros(16)
print (a)
print(a.shape)
b=a.reshape((4,4)) #改變資料的維度為4X4
print(b)
print(b.shape)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
(16,)
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(4, 4)


# array 進階

In [11]:
my_array =np.arange(10)
print(my_array)
print(my_array[0])
print(my_array[0:5]) #取0,1,2,3,4位置的值

[0 1 2 3 4 5 6 7 8 9]
0
[0 1 2 3 4]


In [18]:
a=np.array([[0,1,2,3,4],[5,6,7,8,9]])
print(a)
b=np.array([np.arange(0,5),np.arange(5,10)])
print(b)
c=np.array(np.arange(0,10).reshape((2,5)))
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


## 假設有六組別"Modern Web","DevOps,"Cloud","Big Dat","Security","自我挑戰組"
## 其參加人數分別為56.8.19.14.6.71人

In [5]:
import numpy as np
groups=["Modern Web","DevOps","Cloud","Big Dat","Security","自我挑戰組"]
iman=[56,8,19,14,6,71]
groups_array=np.array(groups)
iman_array=np.array(iman)
print(groups_array)
print(iman_array)

['Modern Web' 'DevOps' 'Cloud' 'Big Dat' 'Security' '自我挑戰組']
[56  8 19 14  6 71]


# 請問大於10人的組別有哪些

In [6]:
# 用人數去鳃選組別
print(iman_array >=10)
print(groups_array[iman_array>=10])

[ True False  True  True False  True]
['Modern Web' 'Cloud' 'Big Dat' '自我挑戰組']


# 除了自我挑戰組之外的組別，人數為何?

In [7]:
#用組別去鳃選人數
print(groups_array !="自我挑戰組")
print(iman_array[groups_array !="自我挑戰組"])

[ True  True  True  True  True False]
[56  8 19 14  6]


# nadarry空直nan無限大inf

In [8]:
nan_array =np.array([56,8,19,14,6,np.nan])
print(nan_array)

[56.  8. 19. 14.  6. nan]


# 生成10組標準常態分配(平均為0，標準差為1的常態分配)隨機變數

In [7]:
normal_samples = np.random.normal(size=10)
print(normal_samples)

[ 1.13134187 -0.39583565  0.62654727 -1.3238366  -0.11473309 -0.60356186
  0.45340818  0.71258445  1.98962938 -0.92716628]


# 生成10組介於0~1之間的隨機變數

In [8]:
uniform_samples = np.random.uniform(size=10)
print(uniform_samples)

[0.74370572 0.50354594 0.51792847 0.87779351 0.34624002 0.70494312
 0.65430743 0.75484616 0.12746388 0.1673644 ]
